"""Deterministic SDLC/STLC artifact generation for Crown AI projects.

Each stage builds on the previous one's output, mirroring the real
requirements -> design -> code -> tests -> non-functional-tests pipeline
Crown AI automates.
"""
from enum import Enum


class Stage(str, Enum):
    requirements = "requirements"
    design = "design"
    code = "code"
    tests = "tests"
    nfr = "nfr"


STAGE_ORDER = [Stage.requirements, Stage.design, Stage.code, Stage.tests, Stage.nfr]

STAGE_LABELS = {
    Stage.requirements: "Requirements Gathering",
    Stage.design: "System Design",
    Stage.code: "Code Generation",
    Stage.tests: "Test Case Generation (STLC)",
    Stage.nfr: "Non-Functional Testing",
}


def stage_index(stage: Stage) -> int:
    return STAGE_ORDER.index(stage)


def generate_artifact_content(stage: Stage, project_name: str, requirements_text: str) -> str:
    if stage == Stage.requirements:
        return (
            f"# Software Requirements Specification -- {project_name}\n\n"
            f"## 1. Overview\nGenerated by Crown AI from the following input:\n\n"
            f"> {requirements_text}\n\n"
            "## 2. Functional Requirements\n"
            "- FR-1: The system shall satisfy the primary user need described above.\n"
            "- FR-2: The system shall provide a usable interface for the primary actor.\n"
            "- FR-3: The system shall validate all user input and surface clear errors.\n\n"
            "## 3. Non-Functional Requirements\n"
            "- NFR-1: Response times under typical load must stay under 2.5s.\n"
            "- NFR-2: The system must be secure by default (authN/authZ enforced).\n"
        )
    if stage == Stage.design:
        return (
            f"# System Design -- {project_name}\n\n"
            "## Architecture\n"
            "- Client (web) <-> API (stateless service) <-> Persistent store\n\n"
            "## Components\n"
            "- API layer: request validation, authentication, business rules\n"
            "- Data layer: durable storage for domain entities\n"
            "- Presentation layer: renders state, handles user interaction\n\n"
            "## Key Design Decisions\n"
            "- Layered architecture chosen for testability and independent scaling.\n"
            "- All state-changing operations are idempotent-safe where practical.\n"
        )
    if stage == Stage.code:
        safe_name = "".join(c if c.isalnum() else "_" for c in project_name.lower()) or "app"
        return (
            f"# Generated scaffold for {project_name}\n"
            f"# module: {safe_name}_service.py\n\n"
            "from dataclasses import dataclass\n\n"
            "@dataclass\n"
            "class Entity:\n"
            "    id: str\n"
            "    name: str\n\n"
            "class Service:\n"
            "    def __init__(self):\n"
            "        self._store = {}\n\n"
            "    def create(self, name: str) -> Entity:\n"
            "        if not name:\n"
            "            raise ValueError('name is required')\n"
            "        entity_id = str(len(self._store) + 1)\n"
            "        entity = Entity(id=entity_id, name=name)\n"
            "        self._store[entity_id] = entity\n"
            "        return entity\n\n"
            "    def get(self, entity_id: str) -> Entity:\n"
            "        if entity_id not in self._store:\n"
            "            raise KeyError('not found')\n"
            "        return self._store[entity_id]\n"
        )
    if stage == Stage.tests:
        return (
            f"# Test Cases (STLC) -- {project_name}\n\n"
            "## TC-1: Create entity with valid name\n"
            "Steps: call create('Alpha') -> Expected: entity returned with id and name set\n\n"
            "## TC-2: Create entity with empty name\n"
            "Steps: call create('') -> Expected: ValueError raised\n\n"
            "## TC-3: Get non-existent entity\n"
            "Steps: call get('missing-id') -> Expected: KeyError raised\n\n"
            "## TC-4: Concurrent creation\n"
            "Steps: call create() from two sessions simultaneously -> Expected: unique ids, no data loss\n"
        )
    if stage == Stage.nfr:
        return (
            f"# Non-Functional Test Report -- {project_name}\n\n"
            "## Performance\n"
            "- p95 response time: 340ms (target < 2500ms) -- PASS\n\n"
            "## Security\n"
            "- Auth required on all mutating endpoints -- PASS\n"
            "- Input validation on all fields -- PASS\n"
            "- No secrets in logs or responses -- PASS\n\n"
            "## Reliability\n"
            "- Error/empty/loading states present on all forms -- PASS\n"
            "- Graceful handling of slow network (>3s) with progress indicator -- PASS\n"
        )
    raise ValueError(f"Unknown stage: {stage}")
